// On-device session state: the server URL the user configured, and — once
// a vault is unlocked — the session token the server issued for it.
//
// SECURITY NOTE ON SCOPE: this class never sees the vault master key. As
// established by reading static/app.js (no deriveKey/argon2/crypto.subtle
// calls in the existing working web client) and internal/adapters/http/
// middleware.go (VaultAuth resolves the key server-side from the token via
// SessionProvider.GetVaultKeyCopy), Argon2id key derivation and the vault
// key both live entirely on the server, keyed off this token. That means
// this app is exactly as trustworthy as the server it's pointed at and the
// network between them — it is a thin, unprivileged client, not a second
// place vault secrets could leak from if it were ever compromised or
// decompiled. Losing this token lets an attacker use the vault for as
// long as the token remains valid (server-side session_timeout_seconds,
// 3600s by default per config.json) — it does not, by itself, decrypt
// anything already at rest.
//
// Backed by EncryptedSharedPreferences: values are AES256-GCM-encrypted
// under a key that is generated by and never leaves the Android Keystore
// (MasterKey.KeyScheme.AES256_GCM). A rooted device or an attacker with
// a different app running as the same UID could still extract it while
// the OS is unlocked — Keystore protects against extraction of the
// *file*, not against another process abusing the same app sandbox.
package com.vault.app.data.local

import android.content.Context
import androidx.security.crypto.EncryptedSharedPreferences
import androidx.security.crypto.MasterKey
import dagger.hilt.android.qualifiers.ApplicationContext
import javax.inject.Inject
import javax.inject.Singleton

@Singleton
class SessionManager @Inject constructor(
    @ApplicationContext context: Context,
) {
    private val masterKey = MasterKey.Builder(context)
        .setKeyScheme(MasterKey.KeyScheme.AES256_GCM)
        .build()

    private val prefs = EncryptedSharedPreferences.create(
        context,
        "vault_session",
        masterKey,
        EncryptedSharedPreferences.PrefKeyEncryptionScheme.AES256_SIV,
        EncryptedSharedPreferences.PrefValueEncryptionScheme.AES256_GCM,
    )

    // ---- Server connection ----

    /** e.g. "http://192.168.1.42:8080" — no trailing slash, validated in the UI layer. */
    var serverBaseUrl: String?
        get() = prefs.getString(KEY_SERVER_URL, null)
        set(value) = prefs.edit().putString(KEY_SERVER_URL, value).apply()

    // ---- Active vault session ----

    var vaultToken: String?
        get() = prefs.getString(KEY_TOKEN, null)
        set(value) = prefs.edit().putString(KEY_TOKEN, value).apply()

    var activeVaultId: String?
        get() = prefs.getString(KEY_VAULT_ID, null)
        set(value) = prefs.edit().putString(KEY_VAULT_ID, value).apply()

    var activeVaultName: String?
        get() = prefs.getString(KEY_VAULT_NAME, null)
        set(value) = prefs.edit().putString(KEY_VAULT_NAME, value).apply()

    fun storeUnlockedSession(vaultId: String, token: String, name: String) {
        prefs.edit()
            .putString(KEY_VAULT_ID, vaultId)
            .putString(KEY_TOKEN, token)
            .putString(KEY_VAULT_NAME, name)
            .apply()
    }

    /** Clears the active session only — server URL is left untouched. */
    fun clearSession() {
        prefs.edit()
            .remove(KEY_TOKEN)
            .remove(KEY_VAULT_ID)
            .remove(KEY_VAULT_NAME)
            .apply()
    }

    // ---- Org/user login session (independent of the vault session above:
    // a device can hold a user session, a vault session, both, or neither
    // — see AuthInterceptor, which sends whichever tokens are present on
    // every request since the two auth paths never read each other's
    // header) ----

    var userToken: String?
        get() = prefs.getString(KEY_USER_TOKEN, null)
        set(value) = prefs.edit().putString(KEY_USER_TOKEN, value).apply()

    var userOrgId: String?
        get() = prefs.getString(KEY_USER_ORG_ID, null)
        set(value) = prefs.edit().putString(KEY_USER_ORG_ID, value).apply()

    var userRole: String?
        get() = prefs.getString(KEY_USER_ROLE, null)
        set(value) = prefs.edit().putString(KEY_USER_ROLE, value).apply()

    var userEmail: String?
        get() = prefs.getString(KEY_USER_EMAIL, null)
        set(value) = prefs.edit().putString(KEY_USER_EMAIL, value).apply()

    fun storeUserSession(token: String, orgId: String, role: String, email: String) {
        prefs.edit()
            .putString(KEY_USER_TOKEN, token)
            .putString(KEY_USER_ORG_ID, orgId)
            .putString(KEY_USER_ROLE, role)
            .putString(KEY_USER_EMAIL, email)
            .apply()
    }

    /** Clears the user/org login session only — leaves any unlocked vault session alone. */
    fun clearUserSession() {
        prefs.edit()
            .remove(KEY_USER_TOKEN)
            .remove(KEY_USER_ORG_ID)
            .remove(KEY_USER_ROLE)
            .remove(KEY_USER_EMAIL)
            .apply()
    }

    // ---- Privacy/security settings — see SettingsScreen. Both default to
    // true (secure-by-default): a fresh install ships protected, and the
    // user opts OUT rather than having to know to opt in. ----

    /** Backs MainActivity's FLAG_SECURE — read at cold start, and re-applied live
     * the moment this changes (see SettingsScreen, which holds the only
     * Activity/window reference available to toggle it immediately). */
    var privacyScreenEnabled: Boolean
        get() = prefs.getBoolean(KEY_PRIVACY_SCREEN_ENABLED, true)
        set(value) = prefs.edit().putBoolean(KEY_PRIVACY_SCREEN_ENABLED, value).apply()

    /** Read by BiometricGateController.onAppForegrounded on every foreground event. */
    var biometricGateEnabled: Boolean
        get() = prefs.getBoolean(KEY_BIOMETRIC_GATE_ENABLED, true)
        set(value) = prefs.edit().putBoolean(KEY_BIOMETRIC_GATE_ENABLED, value).apply()

    private companion object {
        const val KEY_SERVER_URL = "server_base_url"
        const val KEY_TOKEN = "vault_token"
        const val KEY_VAULT_ID = "active_vault_id"
        const val KEY_VAULT_NAME = "active_vault_name"
        const val KEY_USER_TOKEN = "user_token"
        const val KEY_USER_ORG_ID = "user_org_id"
        const val KEY_USER_ROLE = "user_role"
        const val KEY_USER_EMAIL = "user_email"
        const val KEY_PRIVACY_SCREEN_ENABLED = "privacy_screen_enabled"
        const val KEY_BIOMETRIC_GATE_ENABLED = "biometric_gate_enabled"
    }
}
